# back to language cpp to try to bypass osx node failure
language: node_js
node_js:
  - "8"
dist: trusty
sudo: false
branches:
  only:
    - master
# pre-install to bring in the correct version of node via nvm
before_install:
  - npm install
script:
  - sh ./script/git-page.sh
