# back to language cpp to try to bypass osx node failure
language: cpp
sudo: false
os:
  - linux
  - osx
# pre-install to bring in the correct version of node via nvm
before_install:
  - npm install
script:
  - sh ./script/git-page.sh
